const userData = [
  {
    username: "htempest0",
    email: "htempest0@seesaa.net",
    password: "tdDzXbIfu",
    name: "Hersch",
    lastname: "Tempest",
  },
  {
    username: "ihodjetts1",
    email: "ihodjetts1@sitemeter.com",
    password: "apGMGKUuK62O",
    name: "Isidora",
    lastname: "Hodjetts",
  },
  {
    username: "lchampness2",
    email: "lchampness2@europa.eu",
    password: "1SKxwLjKjp",
    name: "Lind",
    lastname: "Champness",
  },
  {
    username: "cstocker3",
    email: "cstocker3@sakura.ne.jp",
    password: "zqwDaqLuxh",
    name: "Cathryn",
    lastname: "Stocker",
  },
  {
    username: "hmckaile4",
    email: "hmckaile4@webnode.com",
    password: "cKNXLVCnt",
    name: "Halli",
    lastname: "McKaile",
  },
  {
    username: "mslessor5",
    email: "mslessor5@narod.ru",
    password: "UC6RZWOQQ3",
    name: "Marlie",
    lastname: "Slessor",
  },
  {
    username: "jscardifield6",
    email: "jscardifield6@ovh.net",
    password: "nPsVMjVbFv",
    name: "Jacqueline",
    lastname: "Scardifield",
  },
  {
    username: "bwahner7",
    email: "bwahner7@e-recht24.de",
    password: "mBUkIR",
    name: "Beverlee",
    lastname: "Wahner",
  },
  {
    username: "dallsep8",
    email: "dallsep8@utexas.edu",
    password: "71VrlSeLQ",
    name: "Doralynne",
    lastname: "Allsep",
  },
  {
    username: "mcisson9",
    email: "mcisson9@cocolog-nifty.com",
    password: "xltOo4Vi39YU",
    name: "Mireielle",
    lastname: "Cisson",
  },
  {
    username: "bcaldecota",
    email: "bcaldecota@feedburner.com",
    password: "7Rcp0J",
    name: "Bobbye",
    lastname: "Caldecot",
  },
  {
    username: "cgrigoireb",
    email: "cgrigoireb@mediafire.com",
    password: "4vZYpf",
    name: "Caty",
    lastname: "Grigoire",
  },
  {
    username: "rfaltinc",
    email: "rfaltinc@earthlink.net",
    password: "T4Iy6yG",
    name: "Rubia",
    lastname: "Faltin",
  },
  {
    username: "crickaertd",
    email: "crickaertd@imageshack.us",
    password: "6iFECzDdFlO",
    name: "Clement",
    lastname: "Rickaert",
  },
  {
    username: "tsidwelle",
    email: "tsidwelle@reddit.com",
    password: "A0iJLE6L",
    name: "Tait",
    lastname: "Sidwell",
  },
  {
    username: "jguyverf",
    email: "jguyverf@acquirethisname.com",
    password: "hlRHwiO71qg",
    name: "Jena",
    lastname: "Guyver",
  },
  {
    username: "aheffernong",
    email: "aheffernong@home.pl",
    password: "Xc3THsG",
    name: "Alisa",
    lastname: "Heffernon",
  },
  {
    username: "klaysonh",
    email: "klaysonh@jigsy.com",
    password: "BTZXoVXG7V",
    name: "Kilian",
    lastname: "Layson",
  },
  {
    username: "cbroomei",
    email: "cbroomei@histats.com",
    password: "jxziRB7cs782",
    name: "Claudell",
    lastname: "Broome",
  },
  {
    username: "lfineyj",
    email: "lfineyj@t.co",
    password: "NEoeLvBKcwt",
    name: "Levin",
    lastname: "Finey",
  },
  {
    username: "cstewardk",
    email: "cstewardk@constantcontact.com",
    password: "0Q7HluM4Gg9",
    name: "Clare",
    lastname: "Steward",
  },
  {
    username: "kgaucherl",
    email: "kgaucherl@mlb.com",
    password: "efErTg6e",
    name: "Kym",
    lastname: "Gaucher",
  },
  {
    username: "sfitzjohnm",
    email: "sfitzjohnm@biblegateway.com",
    password: "wxaiWf",
    name: "Stephen",
    lastname: "Fitzjohn",
  },
  {
    username: "mrowatn",
    email: "mrowatn@columbia.edu",
    password: "48v4Fe9W2k",
    name: "Myrtia",
    lastname: "Rowat",
  },
  {
    username: "plodwigo",
    email: "plodwigo@rediff.com",
    password: "Ks3arcgul5y",
    name: "Perkin",
    lastname: "Lodwig",
  },
  {
    username: "mnewsteadp",
    email: "mnewsteadp@ft.com",
    password: "OKMfLfq",
    name: "Morgun",
    lastname: "Newstead",
  },
  {
    username: "ttonnerq",
    email: "ttonnerq@china.com.cn",
    password: "IyxdJYZzU5a7",
    name: "Trever",
    lastname: "Tonner",
  },
  {
    username: "gweightmanr",
    email: "gweightmanr@bluehost.com",
    password: "wwPKcV",
    name: "Gretchen",
    lastname: "Weightman",
  },
  {
    username: "tpheasants",
    email: "tpheasants@answers.com",
    password: "0oczYeG",
    name: "Toiboid",
    lastname: "Pheasant",
  },
  {
    username: "dbierlingt",
    email: "dbierlingt@edublogs.org",
    password: "TT3gTIzZJZpZ",
    name: "Daryle",
    lastname: "Bierling",
  },
  {
    username: "cnoadsu",
    email: "cnoadsu@princeton.edu",
    password: "mXE0spk9Vqgr",
    name: "Christabel",
    lastname: "Noads",
  },
  {
    username: "sbarkworthv",
    email: "sbarkworthv@shutterfly.com",
    password: "P81Vz5e6",
    name: "Shayne",
    lastname: "Barkworth",
  },
  {
    username: "jpicardow",
    email: "jpicardow@cbc.ca",
    password: "JnNm5GFz",
    name: "Jacynth",
    lastname: "Picardo",
  },
  {
    username: "kbendex",
    email: "kbendex@nifty.com",
    password: "6h2mpkKrym",
    name: "Korey",
    lastname: "Bende",
  },
  {
    username: "javarney",
    email: "javarney@lulu.com",
    password: "sFoXnDo92",
    name: "Joela",
    lastname: "Avarne",
  },
  {
    username: "hwisbyz",
    email: "hwisbyz@google.co.uk",
    password: "IGzmpP",
    name: "Hobard",
    lastname: "Wisby",
  },
  {
    username: "ebeades10",
    email: "ebeades10@theatlantic.com",
    password: "u8XCHzhTnz",
    name: "Enoch",
    lastname: "Beades",
  },
  {
    username: "nmcgahey11",
    email: "nmcgahey11@biblegateway.com",
    password: "U1c4HXp",
    name: "Netta",
    lastname: "McGahey",
  },
  {
    username: "iguyon12",
    email: "iguyon12@senate.gov",
    password: "xasn2rxV",
    name: "Idelle",
    lastname: "Guyon",
  },
  {
    username: "hwhightman13",
    email: "hwhightman13@prnewswire.com",
    password: "aT7Kdv",
    name: "Horten",
    lastname: "Whightman",
  },
  {
    username: "mshergold14",
    email: "mshergold14@moonfruit.com",
    password: "LXnEam2gP0gy",
    name: "Montgomery",
    lastname: "Shergold",
  },
  {
    username: "ssiemandl15",
    email: "ssiemandl15@mac.com",
    password: "nMnvgBiPnwqZ",
    name: "Serge",
    lastname: "Siemandl",
  },
  {
    username: "bstrutley16",
    email: "bstrutley16@narod.ru",
    password: "QiXCZo7O",
    name: "Beau",
    lastname: "Strutley",
  },
  {
    username: "mhadingham17",
    email: "mhadingham17@acquirethisname.com",
    password: "1i2NDJfPC4",
    name: "Marlane",
    lastname: "Hadingham",
  },
  {
    username: "gshreeve18",
    email: "gshreeve18@eepurl.com",
    password: "YSV27fMV",
    name: "Gilberta",
    lastname: "Shreeve",
  },
  {
    username: "glesek19",
    email: "glesek19@dropbox.com",
    password: "DhBYS0A",
    name: "Gladys",
    lastname: "Lesek",
  },
  {
    username: "amocker1a",
    email: "amocker1a@zdnet.com",
    password: "q5ryAH7lcsXy",
    name: "Adrea",
    lastname: "Mocker",
  },
  {
    username: "fhanmer1b",
    email: "fhanmer1b@samsung.com",
    password: "axzE1o",
    name: "Fania",
    lastname: "Hanmer",
  },
  {
    username: "llogsdale1c",
    email: "llogsdale1c@un.org",
    password: "44R9bEP",
    name: "Leland",
    lastname: "Logsdale",
  },
  {
    username: "mmartel1d",
    email: "mmartel1d@netscape.com",
    password: "qmlugJPW8T",
    name: "Marilin",
    lastname: "Martel",
  },
  {
    username: "qfullager1e",
    email: "qfullager1e@liveinternet.ru",
    password: "fmOyvHDUn",
    name: "Quentin",
    lastname: "Fullager",
  },
  {
    username: "bhaggard1f",
    email: "bhaggard1f@google.pl",
    password: "Eutsxwda0ce",
    name: "Berty",
    lastname: "Haggard",
  },
  {
    username: "ntidswell1g",
    email: "ntidswell1g@chicagotribune.com",
    password: "YtHpvt",
    name: "Nonie",
    lastname: "Tidswell",
  },
  {
    username: "tsenogles1h",
    email: "tsenogles1h@washingtonpost.com",
    password: "ffCS0OmM7X",
    name: "Tatiania",
    lastname: "Senogles",
  },
  {
    username: "sbottell1i",
    email: "sbottell1i@scientificamerican.com",
    password: "WO4cNZ6yZ1J",
    name: "Shurlock",
    lastname: "Bottell",
  },
  {
    username: "ksteane1j",
    email: "ksteane1j@nydailynews.com",
    password: "dbSuo6L9L89Y",
    name: "Kitty",
    lastname: "Steane",
  },
  {
    username: "redwardson1k",
    email: "redwardson1k@creativecommons.org",
    password: "JWpafmKETK7f",
    name: "Row",
    lastname: "Edwardson",
  },
  {
    username: "tkornacki1l",
    email: "tkornacki1l@photobucket.com",
    password: "eO97Ci4",
    name: "Timotheus",
    lastname: "Kornacki",
  },
  {
    username: "kfontenot1m",
    email: "kfontenot1m@fotki.com",
    password: "A0gtSI8TDE9q",
    name: "Karen",
    lastname: "Fontenot",
  },
  {
    username: "mcharles1n",
    email: "mcharles1n@google.es",
    password: "z7yShqF",
    name: "Meredith",
    lastname: "Charles",
  },
  {
    username: "dlodevick1o",
    email: "dlodevick1o@wordpress.com",
    password: "bCvgQGPLhvO",
    name: "Duke",
    lastname: "Lodevick",
  },
  {
    username: "mcleverley1p",
    email: "mcleverley1p@xrea.com",
    password: "TLjacUd",
    name: "Mignonne",
    lastname: "Cleverley",
  },
  {
    username: "lbick1q",
    email: "lbick1q@aboutads.info",
    password: "YibHFUll",
    name: "Lance",
    lastname: "Bick",
  },
  {
    username: "mchiese1r",
    email: "mchiese1r@usatoday.com",
    password: "jwhQtdw6rMh",
    name: "Micky",
    lastname: "Chiese",
  },
  {
    username: "jabrey1s",
    email: "jabrey1s@webmd.com",
    password: "uWoAjZ",
    name: "Jonie",
    lastname: "Abrey",
  },
  {
    username: "llowson1t",
    email: "llowson1t@pbs.org",
    password: "Yfl1j26kC0WA",
    name: "Lorene",
    lastname: "Lowson",
  },
  {
    username: "dlacasa1u",
    email: "dlacasa1u@oaic.gov.au",
    password: "881l5Jlbv",
    name: "Drugi",
    lastname: "Lacasa",
  },
  {
    username: "mfance1v",
    email: "mfance1v@opensource.org",
    password: "a9WgVa1H33",
    name: "Mavis",
    lastname: "Fance",
  },
  {
    username: "djaggers1w",
    email: "djaggers1w@sina.com.cn",
    password: "g6QyI2Trw",
    name: "Dionne",
    lastname: "Jaggers",
  },
  {
    username: "abrotherhead1x",
    email: "abrotherhead1x@technorati.com",
    password: "Wbf3aKbu0ni",
    name: "Aindrea",
    lastname: "Brotherhead",
  },
  {
    username: "apedden1y",
    email: "apedden1y@nature.com",
    password: "NsMVu3c13Ygu",
    name: "Alisha",
    lastname: "Pedden",
  },
  {
    username: "mlamplugh1z",
    email: "mlamplugh1z@nhs.uk",
    password: "8juYBLyplCa",
    name: "Mikey",
    lastname: "Lamplugh",
  },
  {
    username: "dfullick20",
    email: "dfullick20@t.co",
    password: "dlKjo1",
    name: "Dag",
    lastname: "Fullick",
  },
  {
    username: "idraycott21",
    email: "idraycott21@aboutads.info",
    password: "CTkwPBm7lhF",
    name: "Ives",
    lastname: "Draycott",
  },
  {
    username: "ibradwell22",
    email: "ibradwell22@parallels.com",
    password: "YrbVcb6D",
    name: "Ingrim",
    lastname: "Bradwell",
  },
  {
    username: "ckemmet23",
    email: "ckemmet23@i2i.jp",
    password: "wppQJm6YYE",
    name: "Cherry",
    lastname: "Kemmet",
  },
  {
    username: "gsanter24",
    email: "gsanter24@instagram.com",
    password: "P56ykKDfG",
    name: "Guillaume",
    lastname: "Santer",
  },
  {
    username: "jdechelle25",
    email: "jdechelle25@mashable.com",
    password: "A9hcgcwoKVU4",
    name: "Jamil",
    lastname: "Dechelle",
  },
  {
    username: "dgummow26",
    email: "dgummow26@mozilla.com",
    password: "lxQiHto",
    name: "Duncan",
    lastname: "Gummow",
  },
  {
    username: "agrayston27",
    email: "agrayston27@army.mil",
    password: "nDMANQku7g",
    name: "Adrianne",
    lastname: "Grayston",
  },
  {
    username: "mmassenhove28",
    email: "mmassenhove28@disqus.com",
    password: "u0hW3kLC7A",
    name: "Mathilda",
    lastname: "Massenhove",
  },
  {
    username: "corganer29",
    email: "corganer29@t.co",
    password: "5kjrA94Nm",
    name: "Chen",
    lastname: "Organer",
  },
  {
    username: "bash2a",
    email: "bash2a@admin.ch",
    password: "ESlypTTytQT",
    name: "Brynna",
    lastname: "Ash",
  },
  {
    username: "nwillwood2b",
    email: "nwillwood2b@arizona.edu",
    password: "TCQu6EHC3nCq",
    name: "Napoleon",
    lastname: "Willwood",
  },
  {
    username: "gbranscomb2c",
    email: "gbranscomb2c@hugedomains.com",
    password: "yM7UWdHgYLEx",
    name: "Giuseppe",
    lastname: "Branscomb",
  },
  {
    username: "azorzini2d",
    email: "azorzini2d@oracle.com",
    password: "MJDcQtiKp",
    name: "Adriane",
    lastname: "Zorzini",
  },
  {
    username: "kgeorgeson2e",
    email: "kgeorgeson2e@wikispaces.com",
    password: "Lp8ahcsnZ6zu",
    name: "Kristoforo",
    lastname: "Georgeson",
  },
  {
    username: "basmus2f",
    email: "basmus2f@twitter.com",
    password: "mgpR7qR8A",
    name: "Brandise",
    lastname: "Asmus",
  },
  {
    username: "aneachell2g",
    email: "aneachell2g@vinaora.com",
    password: "QEldLWqzx",
    name: "April",
    lastname: "Neachell",
  },
  {
    username: "msiddaley2h",
    email: "msiddaley2h@independent.co.uk",
    password: "rpiN8m",
    name: "Mirelle",
    lastname: "Siddaley",
  },
  {
    username: "nbooley2i",
    email: "nbooley2i@ucla.edu",
    password: "sePq2PGrnP4",
    name: "Nicol",
    lastname: "Booley",
  },
  {
    username: "muzielli2j",
    email: "muzielli2j@wufoo.com",
    password: "oQhZ1T5Vm1T2",
    name: "Mae",
    lastname: "Uzielli",
  },
  {
    username: "lchimenti2k",
    email: "lchimenti2k@alibaba.com",
    password: "ZZcAdVu",
    name: "Lydon",
    lastname: "Chimenti",
  },
  {
    username: "ddundredge2l",
    email: "ddundredge2l@soundcloud.com",
    password: "lw1IeH",
    name: "Danila",
    lastname: "Dundredge",
  },
  {
    username: "tvarvara2m",
    email: "tvarvara2m@51.la",
    password: "gbYKMm",
    name: "Tiebout",
    lastname: "Varvara",
  },
  {
    username: "diiannoni2n",
    email: "diiannoni2n@gmpg.org",
    password: "s1LpKO9GNRiP",
    name: "Dorine",
    lastname: "Iiannoni",
  },
  {
    username: "dboggs2o",
    email: "dboggs2o@sbwire.com",
    password: "j4KoV2SPvc",
    name: "Demetris",
    lastname: "Boggs",
  },
  {
    username: "mnappin2p",
    email: "mnappin2p@upenn.edu",
    password: "qzVEYO",
    name: "Maureen",
    lastname: "Nappin",
  },
  {
    username: "creddy2q",
    email: "creddy2q@mit.edu",
    password: "g8TuENPpm",
    name: "Coletta",
    lastname: "Reddy",
  },
  {
    username: "lmullins2r",
    email: "lmullins2r@java.com",
    password: "pRjT0EUKa",
    name: "Loralie",
    lastname: "Mullins",
  },
];

postData = [
  {
    postText: "Need a ABAP Developer and SAP SD Consultant",
    username: "lmullins2r",
  },
  {
    postText: "Need a Javascript Developer and SAP BTP developer",
    username: "creddy2q",
  },
  {
    postText: "Need a Javascript Developer and JAVA developer",
    username: "creddy2q",
  },
  {
    postText:
      "I will create responsive websites in html css javascript react nodejs nextjs",
    username: "mnappin2p",
  },
  {
    postText: "I will develop react js redux firebase web app",
    username: "diiannoni2n",
  },
  {
    postText:
      "Software Engineer - .Net Software Engineer 6 Month Contract Remote ",
    username: "tvarvara2m",
  },
  {
    postText:
      "Frontend Developer Are you a Frontend Developer looking for new and exciting opportunities? If so, then you could be the perfect person to join the Darwin family!",
    username: "aneachell2g",
  },
  {
    postText:
      "Oracle Integration Design Specialist Oracle Integration Design Specialist to support ",
    username: "tvarvara2m",
  },
];
module.exports = { userData, postData };
